EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
linters:
  ErbSafety:
    enabled: true
    # better_html_config: .better-html.yml
  RightTrim:
    enabled: true
    enforced_style: '='
  Layout/TrailingEmptyLines:
    EnforcedStyle: final_blank_line
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
