require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "db/seeds.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "bin/*"

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

# https://github.com/rubocop/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for
    - if
    - unless

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/api/*/entities/**/*"
    - "spec/api/*/entities/**/*"

RSpec/EmptyLineAfterSubject:
  Exclude:
    - "spec/factories/**"

RSpec/ExampleLength:
  Enabled: true
  Max: 10

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MessageSpies:
  EnforcedStyle: receive

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - "config/application.rb"
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: compact

Style/HashAsLastArrayItem:
  EnforcedStyle: braces

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
